/* eslint-disable react-native/no-color-literals */
import { StyleSheet, StatusBar, Dimensions, Platform } from 'react-native';
import GS, { normalizedFontSize, customFont } from '../../GlobeStyle';
const screenHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  safeAreaView: {
    flex: 1,
    backgroundColor: '#fff',
  },
  scrollView: {
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    backgroundColor: '#fff',
    paddingTop: Platform.OS === 'android' ? null : 30,
  },
  contentContainerStyle: {
    paddingTop: StatusBar.currentHeight,
  },
  backButton: {
    position: 'absolute',
    top: StatusBar.currentHeight + 10,
    left: 10,
    zIndex: 100,
    backgroundColor: '#fff',
    borderRadius: 100,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userLocationButton: {
    position: 'absolute',
    top: StatusBar.currentHeight + 10,
    right: 10,
    zIndex: 100,
    backgroundColor: '#fff',
    borderRadius: 100,
    height: 40,
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapContainer: {
    flex: 1,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    top: 0,
  },
  mapView: {
    flex: 1,
  },
  fromButtonsContainer: {
    flexDirection: 'row',
    paddingBottom: 10,
    bottom: 0,
    marginTop: 'auto',
    paddingHorizontal: 20,
    backgroundColor: '#fff',
  },
  cancelButton: {
    flex: 1,
    borderWidth: 2,
    borderColor: GS.secondaryColor,
    borderRadius: 10,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 5,
    backgroundColor: '#fff',
  },
  cancelButtonText: {
    color: GS.secondaryColor,
    fontSize: normalizedFontSize(8),
    fontFamily: customFont.axiformaBold,
  },
  saveButton: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: GS.secondaryColor,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 5,
  },
  disabledSaveButton: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: GS.greyColor,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 5,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: normalizedFontSize(8),
    fontFamily: customFont.axiformaBold,
  },
  areaModalContainer: {
    flex: 1,
    backgroundColor: '#00000050',
  },
  areaModal: {
    maxHeight: screenHeight / 1.3,
    minHeight: screenHeight / 1.5,
    backgroundColor: '#fff',
    marginTop: 'auto',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: 'hidden',
  },
  sectionList: {
    borderRadius: 20,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingHorizontal: 10,
  },
  modalHeaderText: {
    fontSize: normalizedFontSize(9),
    color: GS.textColorGreyDark3,
  },
  modalCloseButton: {
    justifyContent: 'flex-start',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  areaSearchContainer: {
    borderRadius: 10,
    borderColor: '#80808050',
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
    marginVertical: 10,
    paddingHorizontal: 10,
  },
  areaSearchIcon: {
    height: 18,
    width: 18,
    resizeMode: 'contain',
  },
  areaSearchInput: {
    flexGrow: 1,
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  areaTitle: {
    borderBottomWidth: 1,
    borderTopWidth: 1,
    borderColor: '#80808050',
    justifyContent: 'center',
    paddingVertical: 10,
    backgroundColor: '#fff',
  },
  areaTitleText: {
    fontSize: normalizedFontSize(8),
    marginHorizontal: 5,
  },
  areaName: {
    marginHorizontal: 10,
    paddingVertical: 15,
  },
  areaNameText: {
    fontSize: normalizedFontSize(7.5),
  },
  loadingContainer: {
    backgroundColor: '#80808050',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingStyle: {
    padding: 15,
    borderRadius: 10,
  },
  markerFixed: {
    left: '50%',
    marginLeft: -(60 / 2),
    marginTop: -60,
    position: 'absolute',
    top: '50%',
  },
  marker: {
    height: 60,
    width: 60,
    resizeMode: 'contain',
  },
  markerInvalid: {
    tintColor: 'gray',
  },
  mapWraningContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffcccc',
    minHeight: 20,
    paddingVertical: 5,
    borderRadius: 8,
  },
  mapWraningText: {
    color: GS.errorRed,
    fontSize: normalizedFontSize(7),
  },
  viewAddressTypeContainer: {
    justifyContent: 'flex-end',
    backgroundColor: '#fff',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  addressTypeContainer: {
    paddingVertical: 20,
    backgroundColor: '#fff',
  },
  addressTypeButton: {
    flexDirection: 'row',
    paddingHorizontal: 15,
    marginRight: 15,
    marginBottom: 10,
    paddingBottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addressTypeButtonText: {
    color: '#000',
    marginRight: 'auto',
    fontSize: normalizedFontSize(8),
    marginLeft: 20,
  },
  mapFooter: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    marginHorizontal: 20,
  },
  mapButtonContainer: {
    flexDirection: 'row',
    marginTop: 10,
  },
  blurView: {
    height: '100%',
    width: '100%',
    opacity: 60,
    top: 0,
    right: 0,
    left: 0,
    position: 'absolute',
  },
  statusBarPlaceHolder: {
    height: StatusBar.currentHeight,
    backgroundColor: '#fff',

    width: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 3,
  },
  addressFormDock: {
    flex: 1,
    zIndex: 1,
    maxHeight: screenHeight - 40 - StatusBar.currentHeight,
    marginTop: 'auto',
  },
});

export default styles;
