/* eslint-disable react-native/no-color-literals */
import { StyleSheet } from 'react-native';
import GS, { customFont, normalizedFontSize } from '../../GlobeStyle';

const style = StyleSheet.create({
  safeAreaStyle: {
    flex: 1,
    backgroundColor: '#fff',
  },
  mainImage: {
    width: '100%',
    height: '70%',
    maxHeight: 300,
    marginTop: 0,
    marginLeft: 'auto',
    marginRight: 'auto',
    zIndex: -20,
    overflow: 'hidden',
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  infoContainer: {
    width: '90%',
    alignSelf: 'center',
    zIndex: 1,
    marginTop: 'auto',
  },
  closedMessageContainer: {
    flex: 1,
    backgroundColor: '#00000040',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  contentContainerStyle: {
    flexGrow: 1,
  },
  pickUpContainer: {
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: 15,
    marginBottom: -5,
  },
  socialContainer: {
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: 15,
    marginBottom: -5,
    // flexDirection: 'row',
    // justifyContent: 'center',
  },
  social: {
    display: 'flex',
    flexDirection: 'row',
    paddingHorizontal: 5,
    paddingTop: 15,
    paddingBottom: 10,
    width: '100%',
  },
  pickUp: {
    borderRadius: 10,
    display: 'flex',
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 10,
    width: '100%',
  },
  pickUpHeader: {
    fontFamily: customFont.axiformaBold,
    marginBottom: 10,
    fontSize: normalizedFontSize(6.126),
  },
  pickUpSubtext: {
    fontFamily: customFont.axiformaSemiBold,
    marginBottom: 10,
    fontSize: normalizedFontSize(5.526),
    color: '#2b2a29',
  },
  pickUpSubtextGreen: {
    color: '#046951',
  },
  pickUpTextContainer: {
    flex: 1,
    flexDirection: 'column',
  },
  socialMediaContainer: {
    flex: 1,
    flexDirection: 'row',
  },
  socialMediaIcon: {
    marginHorizontal: 5,
  },
  justifyCenter: {
    justifyContent: 'center',
  },
  mediaContainer: {
    flexDirection: 'row',
    marginRight: 5,
    borderRadius: 5,
    paddingHorizontal: 5,
    paddingVertical: 10,
    minWidth: 90,
  },
  socialMediaText: {
    fontSize: 10,
    textTransform: 'capitalize',
    marginRight: 5,
    alignContent: 'center',
  },
  socialMediaLabel: {
    fontSize: 14,
    marginLeft: 5,
    marginTop: 10,
    marginBottom: 0,
  },
  pickUpButtonContainer: {
    display: 'flex',
    alignItems: 'center',
    alignContent: 'center',
    flexDirection: 'row',
    marginLeft: normalizedFontSize(5),
    marginBottom: 10,
  },
  pickUpButton: {
    backgroundColor: '#ffffff',
    paddingTop: normalizedFontSize(2),
    paddingBottom: normalizedFontSize(1),
    alignSelf: 'center',
    borderRadius: 4,
  },
  pickUpButtonText: {
    fontSize: normalizedFontSize(6.5),
    padding: 5,
    paddingLeft: 10,
    paddingRight: 10,
    fontFamily: customFont.axiformaBold,
  },
  addOptionsContainer: {
    paddingHorizontal: 15,
    marginBottom: 10,
  },
  addOptions: {
    borderColor: GS.textColorGrey1,
    borderWidth: normalizedFontSize(0.35),
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 10,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex:2,
    flexWrap: 'wrap',
  },
  addOptionsButton: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: 'white',
    flexGrow: 1,
    margin: 5,
    width:75,
  },
  addOptionsImage: {
    marginBottom: 10,
    height: 30,
    width: 30,
  },
  addOptionsText: {
    fontSize: normalizedFontSize(6.126),
    fontFamily: customFont.axiformaRegular,
    color: GS.lightGrey2,
    textAlign: 'center',
    maxHeight: 12,
    minWidth: 80
  },
  orderDeliveryContainer: {
    display: 'flex',
    flexDirection: 'row',
    borderColor: '#009900',
    borderWidth: 0.5,
    borderRadius: 10,
    padding: 15,
    alignItems: 'center',
  },
  orderDeliveryContainerLeft: {
    display: 'flex',
    flexDirection: 'row',
    flex: 1,
  },
  orderDeliveryContainerText: {
    display: 'flex',
    flexDirection: 'column',
    marginLeft: 10,
    justifyContent: 'space-around',
  },
  orderDeliveryHeader: {
    fontFamily: customFont.axiformaBold,
    fontSize: normalizedFontSize(6.126),
  },
  orderDeliverySubtext: {
    fontFamily: customFont.axiformaRegular,
    fontSize: normalizedFontSize(6.126),
    color: GS.lightGrey2,
  },
  orderDeliveryContainerRight: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  orderDeliveryImage: {
    height: 40,
    width: 40,
    marginRight: 20,
  },
  addressContainerOuter: {
    paddingHorizontal: 15,
    marginBottom: 10,
    marginTop: 15,
  },
  addressContainerInner: {
    display: 'flex',
    flexDirection: 'column',
    marginHorizontal: 10,
  },
  addressTextMarigin: {
    marginBottom: 15,
  },
  addressLine: {
    color: GS.lightGrey2,
    fontFamily: customFont.axiformaRegular,
    marginBottom: 15,
  },
  addressButtonsContainer: {
    display: 'flex',
    flexDirection: 'row',
  },
  addressButtonContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  addressButtonText: {
    marginLeft: 10,
    marginRight: 20,
    fontFamily: customFont.axiformaRegular,
    color: GS.secondaryColor,
    fontSize: normalizedFontSize(5.126),
  },
  reviewHighlightsOuter: {
    paddingHorizontal: 15,
    paddingBottom: 5,
    paddingTop: 15,
    borderColor: GS.textColorGrey1,
    borderWidth: StyleSheet.hairlineWidth * 2,
    backgroundColor: '#F0FFF2',
    marginTop: 10,
  },
  reviewHighlightsInner: {
    display: 'flex',
    flexDirection: 'column',
    marginHorizontal: 10,
  },
  reviewHighlightsHeader: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  reviewHighlightsHeaderText: {
    color: GS.secondaryColor,
    fontSize: normalizedFontSize(6),
  },
  reviewHighlightsBestSellingHeader: {
    marginTop: 8,
    color: GS.lightGrey2,
    display: 'flex',
    flexDirection: 'column',
  },
  reviewHighlightsBestSellingText: {
    marginBottom: 5,
    fontSize: normalizedFontSize(6),
  },
  reviewHighlightsTagsContainer: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  tagContainer: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    margin: 5,
    backgroundColor: '#fff',
    borderColor: GS.textColorGrey1,
    borderWidth: StyleSheet.hairlineWidth * 2,
    borderRadius: 15,
    flexWrap: 'wrap',
    overflow: 'scroll',
  },
  tagText: {
    fontSize: normalizedFontSize(5),
  },
  restDetailsContainerOuter: {
    paddingHorizontal: 15,
    paddingBottom: 10,
    paddingTop: 15,
    borderColor: GS.textColorGrey1,
    // borderWidth: StyleSheet.hairlineWidth * 2,
  },
  restDetailsContainerInner: {
    display: 'flex',
    flexDirection: 'column',
    marginHorizontal: 10,
  },
  restDetailSubtext: {
    marginTop: 7,
    color: GS.lightGrey2,
    fontSize: normalizedFontSize(6),
  },
  restDetailsCategories: {
    marginTop: 5,
    display: 'flex',
    flexDirection: 'row',
  },
  restDetailsCategory: {
    color: GS.secondaryColor,
    fontSize: normalizedFontSize(6),
  },
  restDetailEstimatedCost: {
    marginTop: 5,
    color: '#333333',
    fontSize: normalizedFontSize(6.5),
  },
  restDetailSubtextOtherTags: {
    marginTop: 25,
    fontSize: normalizedFontSize(5),
  },
  restOtherTagsContainer: {
    paddingTop: 5,
    borderColor: '#000000',
  },
  restOtherTagContainer: {
    borderColor: GS.textColorGrey1,
    borderWidth: StyleSheet.hairlineWidth * 2,
    flexWrap: 'wrap',
  },
  restOtherTagsext: {
    fontSize: normalizedFontSize(5.126),
    color: '#000000',
  },
  pickUpBanner: {
    width: '100%',
    resizeMode: 'contain',
    padding: 0,
    margin: 0,
    height: undefined,
    aspectRatio: 1024 / 324,
    marginVertical: 10,
  },
  pickUpBannerImage: {
    height: '100%',
    width: '100%',
    position: 'absolute',
    resizeMode: 'cover',
    zIndex: -1,
    alignSelf: 'center',
  },
  animatedContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#ffffff80',
    zIndex: 10,
  },
  animatedContainer2: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#ffffff',
    zIndex: 10,
  },
});

export default style;
